version: '3.9'
services:
  appname-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - /app/node_modules
      - /app/dist
      - .:/app
