version: '3.9'
services:
  appname-backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - BACKEND_URL=/
        - NODE_ENV=production
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - /app/node_modules
      - /app/dist
      - .:/app